1.- Aquí probamos dos tipos de errores. Se capturan como eventos. Solo habría que escribirlos en el 
código para que saltarán en la ejecución en caso de producirse. Se haría con este código:

process.on('unhandledRejection', (err, p) => {
  console.log('Custom Error: An unhandledRejection occurred')
  console.log(`Custom Error: Rejection: ${err}`)
})

process.on('uncaughtException', err => {
  console.log('Custom Error: An uncaughtException occurred')
  console.log(`Custom Error: Rejection: ${err}`)
})

Ambos se lanzan en caso de haber un error mostrando el mensaje escrito en pantalla. Se ha escrito el
código de prueba en index.js